### ISSUE TITLE
Running in Jetty?

### ISSUE THREAD

**Issue by wdeclerc** [phax/ph-oton#4]
Hi Philip,

Running in Tomcat works well.
But when running RunInJettyPHOTONDEMO_BS4, I get: 
[ERROR] [main] Failed to start Jetty RunInJettyPHOTONDEMO_BS4! -- com.helger.photon.jetty.JettyStarter.run(JettyStarter.java:603)
java.lang.IllegalStateException: No global web scope object has been set!

(Same for RunInJettySMPSERVER_SQL.)

How should I set the global web scope object in this case?

**Comment by phax** [comment]
@wdeclerc How are you running the Jetty? They are "optimized" for running within Eclipse IDE. If e.g. run from IntelliJ, you need to modify the startup directory, because it defaults to "src" if I remember correctly.
Can you also check, if the "WEB-INF/web.xml" file reside in "target/webapp-classes/WEB-INF/web.xml"? Thx

**Comment by wdeclerc** [comment]
I'm using IntelliJ and changing the working directory to the root of the module solved it. 
Thank you!

**Comment by phax** [comment]
Great - thanks for the feedback.
